export const cardsConstants = {
    ZERO: 0,
    CARDS_COUNT_FOR_DESKTOP: 12,
    CARDS_COUNT_FOR_TABLET: 8,
    CARDS_COUNT_FOR_MOBILE: 5,
    CARDS_COUNT_PAGINATION_DESKTOP: 3,
    CARDS_COUNT_PAGINATION_TABLET: 2,
    CARDS_COUNT_PAGINATION_MOBILE: 1,
    SHORT_MOVIE_DURATION: 40,
}